export const meses = [
  "ENE",
  "FEB",
  "MAR",
  "ABR",
  "MAY",
  "JUN",
  "JUL",
  "AGO",
  "SEP",
  "OCT",
  "NOV",
  "DIC",
];

export const indicadoresIgae = [
  "Indicador Global de la Actividad Económica",
  "Actividades primarias",
  "Actividades secundarias",
  "Minería",
  "Generación, transmisión, distribución y comercialización de energía eléctrica, suministro de agua y de gas natural por ductos al consumidor final",
  "Construcción",
  "Industrias manufactureras",
  "Actividades terciarias",
  "Comercio al por mayor",
  "Comercio al por menor",
  "Transportes, correos y almacenamiento",
  "Información en medios masivos",
  "Servicios financieros y de seguros",
  "Servicios inmobiliarios y de alquiler de bienes muebles e intangibles",
  "Servicios profesionales, científicos y técnicos",
  "Servicios de apoyo a los negocios y manejo de residuos y desechos, y servicios de remediación",
  "Servicios educativos",
  "Servicios de salud y de asistencia social",
  "Servicios de esparcimiento culturales y deportivos, y otros servicios recreativos",
  "Servicios de alojamiento temporal y de preparación de alimentos y bebidas",
  "Otros servicios excepto actividades gubernamentales",
  "Actividades legislativas, gubernamentales, de impartición de justicia y de organismos internacionales y extraterritoriales",
];
